import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;

public class Secure_Chat {
	private JTextField message_box;
	private JButton send_btn;
	private JTextArea Chat_Area;
	private JPanel panel;

	// here we throw the IOException just in case the server kahoot's itself
	public Secure_Chat() throws IOException {

		/**then we start the server connection processes
		 Now it might look like a lot but really we just take the IP from the previous input field along with
		 the port. Then Socket does its magic and makes love to the server.
		 **/

		Socket socket = new Socket(Secure_Form.IP_ADDRESS, Secure_Form.PORT);

		// the serverConnection is used for checking the server for any incoming messages encase were caught lacking
		// and you dont wanna be caught lacking or the info clumps up and kills your eyes ;)
		ServerConnection serverConn = new ServerConnection(socket, this);


		//The bufferedReader Is just like a Scanner but it works better for the socket Library
		// The print Writer is used for sending messages across the internet using socket
		BufferedReader clientInput = new BufferedReader(new InputStreamReader(socket.getInputStream()));
		PrintWriter clientOutput = new PrintWriter(socket.getOutputStream(), true);

		//Waiting for connection message from the server and adding it to the chat area
		String serverResponse = clientInput.readLine();
		Chat_Area.append(serverResponse + "\n");

		// reading the username line from the server auto send the name to the server
		serverResponse = clientInput.readLine();
		clientOutput.println(Secure_Form.USERNAME);
		//Chat_Area.append(serverResponse+"\n");

		//we need start checking for incoming messages from the server using a separate thread to not freeze the GUI
		new Thread(serverConn).start();

		//action listener for the send message button which checks to see if we still need to send the server our username
		send_btn.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				//takes in the message from the user and send it to the server
				String message = message_box.getText();
				clientOutput.println(message);
			}
		});
	}

	//gets and sets of course :)

	public void setMessage_box(JTextField message_box) {
		this.message_box = message_box;
	}

	public void setSend_btn(JButton send_btn) {
		this.send_btn = send_btn;
	}

	public void setChat_Area(String chat_Area) {
		Chat_Area.append(chat_Area);
	}

	public void setPanel(JPanel panel) {
		this.panel = panel;
	}

	public JTextField getMessage_box() {
		return message_box;
	}

	public JPanel getPanel() {
		return panel;
	}

	public JButton getSend_btn() {
		return send_btn;
	}

	public JTextArea getChat_Area() {
		return Chat_Area;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
		panel.setBackground(new Color(-11382188));
		final JScrollPane scrollPane1 = new JScrollPane();
		scrollPane1.setBackground(new Color(-11382188));
		panel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		Chat_Area = new JTextArea();
		Chat_Area.setBackground(new Color(-11382188));
		Chat_Area.setEditable(false);
		Chat_Area.setForeground(new Color(-5066062));
		Chat_Area.setText("");
		scrollPane1.setViewportView(Chat_Area);
		message_box = new JTextField();
		message_box.setBackground(new Color(-11382188));
		message_box.setEditable(true);
		message_box.setForeground(new Color(-5066062));
		message_box.setText("");
		panel.add(message_box, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		send_btn = new JButton();
		send_btn.setBackground(new Color(-11382188));
		send_btn.setEnabled(true);
		send_btn.setForeground(new Color(-5066062));
		send_btn.setText("Send");
		panel.add(send_btn, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}
}
