import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

public class Secure_Form {
	private JPanel leftPanel;
	private JButton join_btn;
	private JTextField portField;
	private JTextField userField;
	private JTextField ipField;
	private JLabel ipLabel;
	private JLabel portLabel;
	private JLabel userLabel;

	private static JFrame frame;

	static String IP_ADDRESS;
	static int PORT;
	static String USERNAME;

	public static void main(String[] args) {

		//creating the main frame/window to choose server settings

		frame = new JFrame("Secure Form");
		frame.setContentPane(new Secure_Form().leftPanel);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setBounds(800, 400, 300, 250);
		//frame.pack();
		frame.setVisible(true);
	}

	public Secure_Form() {
		//event listener for the join button that grabs all filled in fields
		join_btn.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {

				IP_ADDRESS = ipField.getText();
				PORT = Integer.parseInt(portField.getText());
				USERNAME = userField.getText();

				// after that we create the new chat window
				// we also use try/catch statement for the Socket declaration in Secure_Chat()'s constructor
				JFrame frame2 = new JFrame("Secure Chat");
				try {
					frame2.setContentPane(new Secure_Chat().getPanel());
				} catch (IOException ioException) {
					ioException.printStackTrace();
				}
				frame2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame2.setBounds(700, 300, 500, 400);
				//frame2.pack();
				frame2.setVisible(true);

				//and for more style points we close the old window :)
				Secure_Form.frame.setVisible(false);
			}
		});
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		leftPanel = new JPanel();
		leftPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1, false, true));
		leftPanel.setBackground(new Color(-11776947));
		panel1.add(leftPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		join_btn = new JButton();
		join_btn.setBackground(new Color(-11382188));
		join_btn.setForeground(new Color(-5066062));
		join_btn.setText("Join Chat");
		leftPanel.add(join_btn, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		portField = new JTextField();
		portField.setBackground(new Color(-11382188));
		portField.setForeground(new Color(-16777216));
		portField.setText("6969");
		leftPanel.add(portField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		userField = new JTextField();
		userField.setBackground(new Color(-11382188));
		userField.setForeground(new Color(-16777216));
		userField.setText("user");
		leftPanel.add(userField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		ipField = new JTextField();
		ipField.setBackground(new Color(-11382188));
		ipField.setForeground(new Color(-16777216));
		ipField.setText("104.210.192.198");
		leftPanel.add(ipField, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		ipLabel = new JLabel();
		ipLabel.setBackground(new Color(-11776947));
		ipLabel.setText("Ip Address");
		leftPanel.add(ipLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		portLabel = new JLabel();
		portLabel.setBackground(new Color(-11776947));
		portLabel.setText("Port");
		leftPanel.add(portLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		userLabel = new JLabel();
		userLabel.setBackground(new Color(-11776947));
		userLabel.setEnabled(true);
		userLabel.setText("Username");
		leftPanel.add(userLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}
}
